config/routes.rb
Rails.application.routes.draw do
  get 'game', to: 'game#new_game'

  get 'score', to: 'game#score'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/game_controller.rb
require 'open-uri'
require 'json'

class GameController < ApplicationController
  def new_game
    @grid = generate_grid(10).shuffle
  end

  def score
    @attempt = params[:attempt].strip
    @grid = params[:grid].split('')
    @time = params[:time].to_f / 1000
    @result = run_game(@attempt, @grid, @time)
  end

  private

  def generate_grid(grid_size)
  Array.new(grid_size / 2) { random_consonant } + Array.new(grid_size / 2) { random_vowel }
  end

  def random_consonant
  (('A'..'Z').to_a - ['A', 'E', 'I', 'O', 'U']).sample
  end

  def random_vowel
    ['A', 'E', 'I', 'O', 'U'].sample
  end

  def run_game(attempt, grid, time)
  contained_grid = contained_in_grid?(attempt, grid)
  result_time = time.round(2)
  translation = translation(attempt)
  score = scoring(attempt, time, translation, contained_grid)
  message = message(attempt, translation, contained_grid)
  { time: result_time, translation: translation, score: score, message: message }
  end

  def contained_in_grid?(attempt, grid)
    attempt.upcase.split('').uniq.all? { |letter| grid.count(letter) >= attempt.upcase.count(letter) }
  end

  def translation(attempt)
    return nil if attempt.empty?
    url = "https://api-platform.systran.net/translation/text/translate?"\
          "source=en&target=fr&key=ec9555fc-fc67-4ecd-94a1-3be23efbf2c8&input=#{attempt}"
    response = JSON.parse(open(url).read)
    translation = response["outputs"][0]["output"]
    attempt != translation ? translation : nil
  end

  def message(attempt, translation, contained_grid)
    if attempt.empty?
      "No answer provided."
    elsif !contained_grid
      "Not in the grid."
    elsif translation.nil?
      "Not an english word."
    else
      "Well done!"
    end
  end

  def scoring(attempt, time, translation, contained_grid)
    translation.nil? || !contained_grid ? 0 : (attempt.length + ((30 - time) / 2)).round(2)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/game_helper.rb
module GameHelper
end

app/views/game/new_game.html.erb
<div class="container text-center">
  <h1>Welcome to the longest word-game!</h1>
  <h2><%= @grid.join(' ') %></h2>

  <div class="answer">
    <form action=" <%= score_path %> ">
      <div class="form-group">
        <label id="label" for="question">What's your best shot?</label>
        <div class="input-group">
          <input type="text" id="question" name="attempt" placeholder="answer" class="form-control" autofocus>
          <span class="input-group-btn">
            <button class="btn btn-danger" type="submit">Score!</button>
          </span>
        </div>
        <input type="hidden" name="grid" value="<%= @grid.join('') %>">
        <input id="time" type="hidden" name="time" value="">
      </div>
    </form>
  </div>

</div>

app/views/game/score.html.erb
<div id="result" class="card text-center">
  <h1>Result</h1>
  <h3><%= "Time: #{@result[:time]}"%></h3>
  <h3><%= "Translation: #{@result[:translation]}"%></h3>
  <h3><%= "Score: #{@result[:score]}"%></h3>
  <h3><%= @result[:message] %></h3>

  <%= link_to "Play another round", game_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsLongestWordGame</title>
    <%= csrf_meta_tags %>

    <link href="https://fonts.googleapis.com/css?family=Roboto:100,400" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>